### ISSUE TITLE
Look for all scenes instead of scenes in folder

### ISSUE THREAD

**Issue by GieziJo** [BennyKok/unity-toolbar-buttons#1]
Hei really cool asset, thanks a lot!

A quick suggestion, instead of looking for scenes in a specific folder you could search the whole project for scenes, a bit slower, but many projects don't rely on having scenes in only one folder:
```csharp
var sceneList = AssetDatabase.GetAllAssetPaths().Where(s => s.EndsWith(".unity")).ToList();
sceneList.Sort();
```
Note that in this way you also directly get the path and don't need to load the object first, and you don't need the `if .unity` statement given the `.Where`

The modified routine looks like this (missing here: the boostrap checker which I don't need, but can easily be added in case):
```csharp
var sceneList = AssetDatabase.GetAllAssetPaths().Where(s => s.EndsWith(".unity")).ToList();
sceneList.Sort();

var a = new GenericMenu();
foreach (var l in sceneList)
{
    a.AddItem(new GUIContent(Path.GetFileNameWithoutExtension(l)), false, () =>
    {
        if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
        {
            EditorSceneManager.OpenScene(l, OpenSceneMode.Single);
        }
    });
}
a.ShowAsContext();
```

Again, thanks a lot for your great work! Let me know if this is something you would like to include, I could open a pull request.

Cheers
Giezi

**Comment by BennyKok** [comment]
Oh hey! Didn't know there is a method to get all scenes path directly, would definitely love that feature, feel free to do a pull request!

**Comment by GieziJo** [comment]
Implemented in pull request #2, see notes about Bootstarp scene

**Comment by RunninglVlan** [comment]
Nice one. But could this be improved by remembering last scene folder? So that if we loaded a scene from /Scenes, we wouldn't need to go there on the next load.
Or maybe select the folder in which current scene is located
What do you think, @GieziJo?

**Comment by RunninglVlan** [comment]
#2
